=== hmcts/cpp-context-staging-bulkscan/stagingbulkscan-event/stagingbulkscan-event-processor/src/yaml/json/schema/stagingbulkscan.events.defendant-financial-means-updated.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/json/schemas/stagingbulkscan/events/stagingbulkscan.events.defendant-financial-means-updated.json",
  "type": "object",
  "properties": {
    "scanDocumentId": {
      "$ref": "http://justice.gov.uk/core/courts/courtsDefinitions.json#/definitions/uuid"
    },
    "income": {
      "$ref": "http://justice.gov.uk/stagingbulkscan/domain/income.json"
    },
    "benefits": {
      "$ref": "http://justice.gov.uk/stagingbulkscan/domain/benefits.json"
    },
    "employment": {
      "$ref": "http://justice.gov.uk/stagingbulkscan/domain/employment.json"
    },
    "employer": {
      "$ref":"http://justice.gov.uk/stagingbulkscan/domain/employer.json"
    },
    "nationalInsuranceNumber": {
      "type": "string"
    },
    "sjpAllFinancialMeans": {
      "$ref": "http://justice.gov.uk/stagingbulkscan/domain/all-financial-means.json"
    }
  },
  "required": [
    "scanDocumentId",
    "sjpAllFinancialMeans"
  ]
}

=== hmcts/cpp-context-staging-bulkscan/stagingbulkscan-event/stagingbulkscan-event-processor/src/test/resources/stagingbulkscan.events.defendant-financial-means-updated.json
{
  "scanDocumentId": "50770ba9-37ea-4713-8cab-fe5bf1202716",
  "income": {
  },
  "benefits": {
    "claimed": true,
    "type": "free text describing benefits type"
  },
  "nationalInsuranceNumber": "AE123456C",
  "sjpAllFinancialMeans": {
    "caseId": "8a2b4656-f2b8-4cdd-abb4-46376db24bbf",
    "defendantId": "50770ba9-37ea-4713-8cab-fe5bf1202716",
    "income": {
    },
    "benefits": {
      "claimed": true,
      "type": "free text describing benefits type"
    }
  }
}
