=== hmcts/cpp-context-staging-bulkscan/stagingbulkscan-json/src/main/resources/json/schema/scan-envelope.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/stagingbulkscan/domain/scan-envelope.json",
  "type": "object",
  "properties": {
    "scanEnvelopeId": {
      "$ref": "http://justice.gov.uk/core/courts/courtsDefinitions.json#/definitions/uuid"
    },
    "envelopeClassification": {
      "type": "string"
    },
    "vendorPOBox": {
      "type": "string"
    },
    "jurisdiction": {
      "type": "string"
    },
    "vendorOpeningDate": {
      "type": "string",
      "format": "date-time"
    },
    "zipFileCreatedDate": {
      "type": "string",
      "format": "date-time"
    },
    "zipFileName": {
      "type": "string"
    },
    "extractedDate": {
      "type": "string",
      "format": "date-time"
    },
    "notes": {
      "type": "string"
    },
    "associatedScanDocuments": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "http://justice.gov.uk/stagingbulkscan/domain/scan-document.json"
      }
    }
  },
  "required": [
    "scanEnvelopeId",
    "zipFileName",
    "associatedScanDocuments",
    "extractedDate"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-staging-bulkscan/stagingbulkscan-command/stagingbulkscan-command-handler/src/test/resources/stagingbulkscan.command.register-scan-envelope.json
{
  "scanEnvelopeId": "fab947a3-c50c-4dbb-accf-b2758b1d2d6a",
  "zipFileName": "1836104010001_27-11-2019-11-52-09.zip",
  "associatedScanDocuments": [
    {
      "scanDocumentId": "fab947a3-c51c-4dbb-accf-b2758b1d2d6d",
      "fileName": "18361040100010001.pdf",
      "caseUrn": "12295672",
      "prosecutorId": "AAAJJ11",
      "prosecutorName": "TFL",
      "documentControlNumber": "18361040100010001",
      "vendorReceivedDate": "2019-09-28T08:00:00.000Z",
      "documentName": "Form SJPN",
      "scanningDate": "2019-09-28T10:46:03.123Z",
      "nextAction": "destroy",
      "nextActionDate": "2019-12-27T10:46:03.123Z",
      "notes": "Sample PDF file",
      "status": "PENDING",
      "statusUpdatedDate": "2019-12-12T09:27:15Z"
    }
  ],
  "extractedDate": "2019-09-28T11:03:00.000Z",
  "envelopeClassification": "supplementary_evidence",
  "vendorPOBox": "1959",
  "jurisdiction": "Crime",
  "vendorOpeningDate": "2019-09-27T10:46:03.123Z",
  "zipFileCreatedDate": "2019-09-28T10:46:03.123Z",
  "notes": "Sample Zip "
}

=== hmcts/cpp-context-staging-bulkscan/stagingbulkscan-integration-test/src/test/resources/stub-data/stagingbulkscan.scan-envelope-with-financial-means-for-followup.json
{
  "scanEnvelopeId": "${scanEnvelopeId}",
  "zipFileName": "TEST.zip",
  "associatedScanDocuments": [
    {
      "scanDocumentId": "${scanDocumentId}",
      "fileName": "${documentFileName}",
      "caseUrn": "12295672",
      "prosecutorAuthorityId": "AAAJJ11",
      "documentControlNumber": "ABCDEFGHI",
      "documentName": "SJPMC100",
      "scanningDate": "${dateTime}",
      "manualIntervention": "No",
      "nextAction": "ABCDEF",
      "nextActionDate": "${dateTime}",
      "vendorReceivedDate": "${dateTime}",
      "notes": "ABCDEFGHIJK",
      "status": "PENDING",
      "statusUpdatedDate": "${dateTime}",
      "mc100s": {
        "employed": true,
        "niNumber": "AE123456C",
        "noIncome": true,
        "unemployed": false,
        "selfEmployed": false,
        "averageIncome": "4556",
        "payrollNumber": "88989",
        "claimBenefits": false,
        "frequencyWeekly": false,
        "frequencyYearly": false,
        "frequencyMonthly": true,
        "nameOfOrganization": "abc",
        "employerAddressCity": "london",
        "employerAddressLine1": "100",
        "employerAddressLine2": "wellesley grove",
        "employerAddressLine3": "croyon",
        "frequencyFortnightly": false,
        "otherEmploymentStatus": false,
        "employerAddressPostCode": "W1T 1JY"
      }
    }
  ],
  "extractedDate": "${dateTime}",
  "envelopeClassification": "ABCDEFGHIJ",
  "vendorPOBox": "1953",
  "jurisdiction": "ABCDEFGHIJ",
  "vendorOpeningDate": "${dateTime}",
  "zipFileCreatedDate": "${dateTime}",
  "notes": "TEST NOTES"
}

=== hmcts/cpp-context-staging-bulkscan/stagingbulkscan-command/stagingbulkscan-command-handler/src/test/resources/stagingbulkscan.command.register-scan-envelope_mandatory.json
{
  "scanEnvelopeId": "fab947a3-c50c-4dbb-accf-b2758b1d2d6a",
  "zipFileName": "1836104010001_27-11-2019-11-52-09.zip",
  "associatedScanDocuments": [
    {
      "scanDocumentId": "fab947a3-c51c-4dbb-accf-b2758b1d2d6d",
      "vendorReceivedDate": "2019-09-28T08:00:00.000Z",
      "documentName": "SJON",
      "fileName": "18361040100010001.pdf",
      "status": "PENDING",
      "statusUpdatedDate": "2019-12-12T09:27:15Z"
    }
  ],
  "extractedDate": "2019-09-28T11:03:00.000Z"
}
