=== hmcts/cpp-context-staging-bulkscan/stagingbulkscan-command/stagingbulkscan-command-handler/src/raml/json/schema/stagingbulkscan.command.expire-document.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/stagingbulkscan/command/stagingbulkscan.command.expire-document.json",
  "type": "object",
  "properties": {
    "scanEnvelopeId": {
      "$ref": "http://justice.gov.uk/core/courts/courtsDefinitions.json#/definitions/uuid"
    },
    "scanDocumentId": {
      "$ref": "http://justice.gov.uk/core/courts/courtsDefinitions.json#/definitions/uuid"
    },
    "expireDate": {
      "type": "string",
      "format": "date-time"
    },
    "errors": {
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/stagingbulkscan/json/schemas/problem.json"
      }
    }
  },
  "required": [
    "scanEnvelopeId",
    "scanDocumentId",
    "expireDate"

  ]
}

=== hmcts/cpp-context-staging-bulkscan/stagingbulkscan-command/stagingbulkscan-command-handler/src/raml/json/stagingbulkscan.command.expire-document.json
{
  "scanEnvelopeId": "726b6391-7bc2-445a-8a0c-9bcfd963702e",
  "scanDocumentId" : "ec998ef3-4775-4166-9ad8-f5eeba78ded1",
  "expireDate": "2019-11-12T09:27:12Z",
  "errors": [
    {
      "code": "INVALID_FILE_TYPE",
      "values": [
        {
          "key": "fileType",
          "value": "application/incorrect"
        }
      ]
    }
  ]
}
