=== hmcts/cpp-context-staging-bulkscan/stagingbulkscan-command/stagingbulkscan-command-handler/src/raml/json/schema/stagingbulkscan.command.update-defendant-details.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/stagingbulkscan/command/stagingbulkscan.command.update-scan-document-status.json",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "http://justice.gov.uk/core/courts/courtsDefinitions.json#/definitions/uuid"
    },
    "scanDocumentId": {
      "$ref": "http://justice.gov.uk/core/courts/courtsDefinitions.json#/definitions/uuid"
    },
    "scanEnvelopeId": {
      "$ref": "http://justice.gov.uk/core/courts/courtsDefinitions.json#/definitions/uuid"
    },
    "email": {
      "type": "string"
    },
    "caseId": {
      "$ref": "http://justice.gov.uk/core/courts/courtsDefinitions.json#/definitions/uuid"
    },
    "title": {
      "$ref": "http://justice.gov.uk/stagingbulkscan/domain/title.json"
    },
    "firstName": {
      "type": "string",
      "minLength": 1,
      "maxLength": 255
    },
    "lastName": {
      "type": "string",
      "minLength": 1,
      "maxLength": 255
    },
    "dateOfBirth": {
      "type": "string"
    },
    "gender": {
      "$ref": "http://justice.gov.uk/stagingbulkscan/domain/gender.json"
    },
    "address": {
      "$ref": "http://justice.gov.uk/stagingbulkscan/domain/address.json"
    },
    "contactNumber": {
      "$ref": "http://justice.gov.uk/stagingbulkscan/domain/contact-details.json"
    },
    "nationalInsuranceNumber": {
      "type": "string"
    }
  },
  "required": [
    "scanEnvelopeId",
    "scanDocumentId"
  ]
}

=== hmcts/cpp-context-staging-bulkscan/stagingbulkscan-command/stagingbulkscan-command-handler/src/raml/json/stagingbulkscan.command.update-defendant-details.json
{
  "scanEnvelopeId": "726b6391-7bc2-445a-8a0c-9bcfd963702e",
  "scanDocumentId" : "ec998ef3-4775-4166-9ad8-f5eeba78ded1",
  "id": "f06f6539-2a7c-4bc8-bca3-f1b17ebcfa47",
  "title":"Dr",
  "firstName": "David",
  "lastName": "SMITH",
  "dateOfBirth": "1980-07-15",
  "gender": "Male",
  "email": "email@email.com",
  "address": {
    "address1": "14 Shaftesbury Road",
    "address2": "London",
    "address3": "England",
    "address4": "UK",
    "address5": "Greater London",
    "postcode": "W1T 1JY"
  },
  "contactNumber": "07123456789",
  "nationalInsuranceNumber": "QQ 12 34 56 C"
}
